### ISSUE TITLE
Add Education Service Center (ESC) Region Boundaries to Map and Check for Changes to School Districts

### ISSUE THREAD

**Issue by coregis** [coregis/cbf-programs-map-2023#16]
- [x] Download ESC Region boundaries and create vector tileset in Mapbox
- [x] Add ESC Region boundaries to map
- [x] Duplicate drop-down for School Districts and use for ESC Regions
- [x] Check for updated School District Boundaries and replace vector tileset if necessary

**Comment by coregis** [comment]
There are many, many differences between the current school district layer we are using (texas_districts_1882_v4) and the most recently published version (Current_Districts_2023) however, most of them look like this so I do not think it is worth swapping them out at this point
![image](https://github.com/coregis/cbf-programs-map-2023/assets/8813214/91c6c334-2e6f-4243-abf8-d665be779cef)

**Comment by eldang** [comment]
Interesting!  I'm not sure exactly what the scale we're looking at is, but it almost looks like it could just be a difference in simplification or minor reprojection glitches.  Unless the screenshot is of a much larger area than I'm thinking, this does seem safe to ignore.

**Comment by eldang** [comment]
Is the ESC name field in the tiles just `NAME`, like with the school districts?

**Comment by coregis** [comment]
> Is the ESC name field in the tiles just `NAME`, like with the school districts?

Somewhat counterintuitively, the one you want appears to be CITY
![image](https://github.com/coregis/cbf-programs-map-2023/assets/8813214/471ac70d-1ff5-47fb-bf15-18bf4e75362c)
