### ISSUE TITLE
Remove Senate District from all pop-ups

### ISSUE THREAD

**Issue by coregis** [coregis/cbf-programs-map-2023#8]
It looks like there is a bit of code that is still populating the Senate District in all pop-ups; I commented out lines 271-287 in onload.js but that kills the entire pop-up. Seems like there's some interaction going on with multiple functions in functions.js, but I don't really understand how and I'm reluctant to start mucking around in there since we need to show this to CBF tomorrow. If you have time will you please comment out/disable/nuke etc the functions and code to remove any reference to Senate or House Districts in the popups? If you don't have time no worries we can go with what we have for tomorrow.

**Comment by eldang** [comment]
👍🏼 I will have time this afternoon, just wrapping up the pull request for that other project and then I can take a look.  Is #5 up to date with the current state of the code?  If so, I'll start from there.

**Comment by eldang** [comment]
Resolved by #10, it just didn't auto-close because that wasn't a merge to `main`.
